### PR TITLE
Embeddable typography component

### PR DESCRIPTION
**Pull request by dhotson**
Usually the typography component is included at the top level e.g
```scss
@import "asimov-typography/component";
```

But for the Tasks chrome extension we need to include the typography component inside an element
so that the styles are scoped to a limited part of the page (i.e. it doesn't have a html/body element).

e.g.
```scss
#__x_99designs-tasks-dialog {
  @import "asimov-typography/component";
}
```

### CODE REVIEW

**Comment by xzyfer** [comment]
:+1: if this compiles correctly with Libsass.

**Comment by dhotson** [comment]
Cool, yep, seems to compile as expected.

What's the release process for our asimov components? Do I just need to tag in git?

**Comment by xzyfer** [comment]
Bump the version in `bower.json` and create a GH release with the release notes.

**Comment by dhotson** [comment]
Look ok? https://github.com/99designs/asimov-typography/releases/tag/2.0.2

**Pull request merged**
